config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/contact'

  resources :contracts

  root to: 'welcome#index'
end

app/models/contract.rb
class Contract < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: [:show, :edit, :update, :destroy]

  # GET /contracts
  # GET /contracts.json
  def index
    @contracts = Contract.all
  end

  # GET /contracts/1
  # GET /contracts/1.json
  def show
  end

  # GET /contracts/new
  def new
    @contract = Contract.new
  end

  # GET /contracts/1/edit
  def edit
  end

  # POST /contracts
  # POST /contracts.json
  def create
    @contract = Contract.new(contract_params)

    respond_to do |format|
      if @contract.save
        format.html { redirect_to @contract, notice: 'Contract was successfully created.' }
        format.json { render :show, status: :created, location: @contract }
      else
        format.html { render :new }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contracts/1
  # PATCH/PUT /contracts/1.json
  def update
    respond_to do |format|
      if @contract.update(contract_params)
        format.html { redirect_to @contract, notice: 'Contract was successfully updated.' }
        format.json { render :show, status: :ok, location: @contract }
      else
        format.html { render :edit }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contracts/1
  # DELETE /contracts/1.json
  def destroy
    @contract.destroy
    respond_to do |format|
      format.html { redirect_to contracts_url, notice: 'Contract was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contract
      @contract = Contract.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contract_params
      params.require(:contract).permit(:title, :ref, :region, :uploadedBy, :savings, :dept, :supplier, :validFrom, :validTo)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contracts/_form.html.erb
<%= form_for(@contract) do |f| %>
  <% if @contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
      <% @contract.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :ref %><br>
    <%= f.number_field :ref %>
  </div>
  <div class="field">
    <%= f.label :region %><br>
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :uploadedBy %><br>
    <%= f.text_field :uploadedBy %>
  </div>
  <div class="field">
    <%= f.label :savings %><br>
    <%= f.number_field :savings %>
  </div>
  <div class="field">
    <%= f.label :dept %><br>
    <%= f.number_field :dept %>
  </div>
  <div class="field">
    <%= f.label :supplier %><br>
    <%= f.text_field :supplier %>
  </div>
  <div class="field">
    <%= f.label :validFrom %><br>
    <%= f.datetime_select :validFrom %>
  </div>
  <div class="field">
    <%= f.label :validTo %><br>
    <%= f.datetime_select :validTo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contracts/edit.html.erb
<h1>Editing Contract</h1>

<%= render 'form' %>

<%= link_to 'Show', @contract %> |
<%= link_to 'Back', contracts_path %>

app/views/contracts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contracts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Ref</th>
      <th>Region</th>
      <th>Uploadedby</th>
      <th>Savings</th>
      <th>Dept</th>
      <th>Supplier</th>
      <th>Validfrom</th>
      <th>Validto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contracts.each do |contract| %>
      <tr>
        <td><%= contract.title %></td>
        <td><%= contract.ref %></td>
        <td><%= contract.region %></td>
        <td><%= contract.uploadedBy %></td>
        <td><%= contract.savings %></td>
        <td><%= contract.dept %></td>
        <td><%= contract.supplier %></td>
        <td><%= contract.validFrom %></td>
        <td><%= contract.validTo %></td>
        <td><%= link_to 'Show', contract %></td>
        <td><%= link_to 'Edit', edit_contract_path(contract) %></td>
        <td><%= link_to 'Destroy', contract, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contract', new_contract_path %>

app/views/contracts/new.html.erb
<h1>New Contract</h1>

<%= render 'form' %>

<%= link_to 'Back', contracts_path %>

app/views/contracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @contract.title %>
</p>

<p>
  <strong>Ref:</strong>
  <%= @contract.ref %>
</p>

<p>
  <strong>Region:</strong>
  <%= @contract.region %>
</p>

<p>
  <strong>Uploadedby:</strong>
  <%= @contract.uploadedBy %>
</p>

<p>
  <strong>Savings:</strong>
  <%= @contract.savings %>
</p>

<p>
  <strong>Dept:</strong>
  <%= @contract.dept %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @contract.supplier %>
</p>

<p>
  <strong>Validfrom:</strong>
  <%= @contract.validFrom %>
</p>

<p>
  <strong>Validto:</strong>
  <%= @contract.validTo %>
</p>

<%= link_to 'Edit', edit_contract_path(@contract) %> |
<%= link_to 'Back', contracts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Conmgmt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="container">
    <ul class="nav nav-tabs">

<%= link_to "Home", root_path %>
<%= link_to "About", welcome_about_path %>
<%= link_to "Staff", root_path %>
<%= link_to "Contracts", contracts_path %>
<%= link_to "Login", root_path %>
<%= link_to "Contact", welcome_contact_path %>
</ul>
<%= yield %>
</div>
</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>